name: covid19model
dependencies:
  - r-bayesplot
  - r-data.table
  - r-envstats
  - r-lubridate
  - r-gdata
  - r-ggpubr
  - r-tidyr
  - r-dplyr
  - r-rstan
  - r-svglite
  - r-jsonlite
channels:
  - conda-forge
